---
extends:
  - eslint:recommended
  - plugin:vue/strongly-recommended
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - vue
  - prettier

env:
  browser: true
  node: true
  jest: true

rules:
  no-console: 1
  no-debugger: 1
  no-inline-comments: 1
  spaced-comment: 1
  multiline-comment-style: 1
  vue/array-bracket-spacing: 1
  vue/arrow-spacing: 1
  vue/block-spacing: 1
  vue/comma-dangle:
    - error
    - only-multiline
  vue/component-definition-name-casing: 2
  vue/component-name-in-template-casing: 2
  vue/eqeqeq: 1
  vue/html-self-closing:
    - 1
    - html:
        normal: never
        void: always
  vue/key-spacing: 2
  vue/keyword-spacing: 1
  vue/match-component-file-name:
    - 2
    - extensions:
        - .jsx
        - .tsx
        - .vue
  vue/max-attributes-per-line:
    - 1
    - singleline: 3
  vue/no-deprecated-scope-attribute: 2
  vue/no-deprecated-slot-attribute: 2
  vue/no-deprecated-slot-scope-attribute: 2
  vue/no-empty-pattern: 2
  vue/no-irregular-whitespace: 2
  vue/no-reserved-component-names: 2
  vue/no-static-inline-styles: 2
  vue/no-v-html: 2
  vue/object-curly-spacing:
    - 2
    - always
  vue/padding-line-between-blocks: 2
  vue/singleline-html-element-content-newline: 0
  vue/space-infix-ops: 2
  vue/space-unary-ops:
    - 2
    - words: true
      nonwords: false
  vue/this-in-template: 2
  vue/v-on-style:
    - 2
    - longform
  vue/v-on-function-call: 2
  vue/v-slot-style:
    - 2
    - default: longform
      named: longform
  vue/valid-v-bind-sync: 2
  vue/valid-v-slot: 2

parserOptions:
  parser: babel-eslint

settings:
  import/external-module-folders:
    - ./server/frontend/node_modules
