dist: trusty
sudo: false
language: python
python:
    - 2.7
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install -r requirements.txt
    - pip install --upgrade codecov pytest-flake8 pytest-pylint pytest-cov pytest-django
script:
    - cd server
    - PYTHONPATH=.. python -m pytest -v --cov=.. --cov-config=.coveragerc --ignore ../server ..
    - PYTHONPATH=.. python -m pytest -v --cov=.. --cov-config=.coveragerc --cov-append .
    - cd ..
after_success:
    - codecov
