dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
before_install:
    - pip install --upgrade setuptools pip
    - pip install --upgrade virtualenv
install:
    - pip --version
    - virtualenv --version
    - git --version
before_script:
    - pip install -r server/requirements.txt
    - pip install --upgrade codecov
script:
    - python -m pytest
after_success:
    - codecov -X gcov
deploy:
    provider: pypi
    user: truber
    password:
        secure: Mu/+/+tbRRSNv2vHYrkOtjm9yCQl9luvdR3M7vq4BOEXd1NEZWR/sHpxOnV97QHINpGqQurUkHE8osrUBCXGkid2G/83HCkCmdwJ53PAdR+ddqz3TPeFX4EsW9j0YuiSABp9Em9EJ1LhIbUAo88GfY55xr1jPS0EaNS1bB8L5Yo=
    on:
        tags: true
