---
version: "3.7"
services:

  backend:
    container_name: fuzzmanager
    build: .
    pull_policy: never
    image: mozillasecurity/fuzzmanager:compose

    depends_on:
      - database
      - redis

    volumes:
      - userdata:/data
      - ./server/server/settings_docker.py:/src/server/server/settings_docker.py:ro

    ports:
      - "8000:80"

  celery-beat:
    container_name: fm-celery-beat
    image: mozillasecurity/fuzzmanager:compose
    pull_policy: never

    command: celery -A celeryconf beat -l info

    depends_on:
      - backend
      - redis

    volumes:
      - ./server/server/settings_docker.py:/src/server/server/settings_docker.py:ro

  celery-cron-worker:
    container_name: fm-celery-cron-worker
    image: mozillasecurity/fuzzmanager:compose
    pull_policy: never

    command: celery -A celeryconf worker -l info -c 4 -n cron@%h -Q cron

    depends_on:
      - backend
      - database
      - redis

    volumes:
      - userdata:/data
      - ./server/server/settings_docker.py:/src/server/server/settings_docker.py:ro

  celery-worker:
    container_name: fm-celery-worker
    image: mozillasecurity/fuzzmanager:compose
    pull_policy: never

    command: celery -A celeryconf worker -l info -n worker@%h -Q celery

    depends_on:
      - backend
      - database
      - redis

    volumes:
      - userdata:/data
      - ./server/server/settings_docker.py:/src/server/server/settings_docker.py:ro

  database:
    container_name: fuzzmanager-db
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_USER: fuzzmanager
      MYSQL_PASSWORD: mozilla1234
      MYSQL_DATABASE: fuzzmanager
      MYSQL_ROOT_PASSWORD: mozilla6789

    volumes:
      - mysql:/var/lib/mysql

  redis:
    container_name: fuzzmanager-redis
    image: redis:7-alpine

volumes:
  userdata:
    driver: local
  mysql:
    driver: local
