[build-system]
requires = ["setuptools>=64", "setuptools_scm>8"]
build-backend = "setuptools.build_meta"

[project]
name = "WebCompatManager"
requires-python = ">=3.9"
authors = [
    {name = "Christian Holler", email = "choller@mozilla.com"},
    {name = "Jesse Schwartzentruber", email = "jschwartzentruber@mozilla.com"},
]
description = "A WebCompat management tools collection"
keywords = ["test", "testing"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Testing",
]
license = {text = "MPL 2.0"}
maintainers = [
    {name = "Mozilla Fuzzing Team", email = "fuzzing@mozilla.com"},
]
dynamic = ["readme", "version"]
dependencies = [
    "jsonpath-ng",
    "jsonschema>=4.18.0",
    "python-dateutil",
]

[project.optional-dependencies]
dev = ["pre-commit", "tox"]
docker = [
    "gunicorn~=22.0.0",
    "mozilla-django-oidc~=4.0.1",
    "mysqlclient~=2.2.4",
]
server = [
    "celery~=5.3.5",
    "crispy-bootstrap3",
    "django~=4.2.7",
    "django-crispy-forms~=2.1",
    "django-enumfields~=2.1.1",
    "django-notifications-hq~=1.8.3",
    "djangorestframework~=3.15.1",
    "pyyaml",
    "redis[hiredis]",
    "whitenoise~=6.6.0",
]

[project.urls]
Homepage = "https://github.com/MozillaSecurity/WebCompatManager"
Issues = "https://github.com/MozillaSecurity/WebCompatManager/issues"
Repository = "https://github.com/MozillaSecurity/WebCompatManager.git"

[tool.black]
target-version = ["py39"]

[tool.coverage.report]
exclude_lines = [
    "@(abc.)?abstract*",
    "except ImportError(.*):",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "pragma: no cover",
]

[tool.coverage.run]
omit = [
    "*/dist/*",
    "*/tests/*",
    "*/.tox/*",
    "*/.eggs/*",
]

[tool.isort]
known_first_party = [
    "reportmanager",
    "webcompat",
]
profile = "black"

[tool.pytest.ini_options]
log_level = "DEBUG"
DJANGO_SETTINGS_MODULE = "server.settings_test"
pythonpath = [".", "server"]
addopts = ["-v", "--cov=.", "--cov-report", "term-missing"]
filterwarnings = [
    'ignore:"@coroutine" decorator:DeprecationWarning:aiohttp',
    'ignore:You passed a bytestring:DeprecationWarning:flake8.options.config',
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:celery.canvas",
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:yaml",
]
norecursedirs = [
    ".*",
    "build",
    "dist",
]

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["webcompat", "webcompat.schemas"]

[tool.setuptools_scm]
