[build-system]
requires = ["setuptools >= 43", "wheel", "setuptools_scm[toml] >= 3.4"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37"]

[tool.coverage.run]
omit = [
    "*/setup.py",
    "*/dist/*",
    "*/tests/*",
    "*/.tox/*",
    "*/.eggs/*",
]

[tool.isort]
known_first_party = [
    "Collector",
    "CovReporter",
    "EC2StatusReporter",
    "FTB",
    "Reporter",
    "TaskStatusReporter",
    "covmanager",
    "crashmanager",
    "ec2spotmanager",
    "taskmanager",
]
profile = "black"

[tool.pytest.ini_options]
log_level = "DEBUG"
DJANGO_SETTINGS_MODULE = "server.settings_test"
python_paths = [".", "server"]
addopts = ["-v", "--cov=.", "--cov-report", "term-missing"]
filterwarnings = [
    'ignore:"@coroutine" decorator:DeprecationWarning:aiohttp',
    'ignore:You passed a bytestring:DeprecationWarning:flake8.options.config',
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:celery.canvas",
    "ignore:Using or importing the ABCs from 'collections':DeprecationWarning:yaml",
]

[tool.setuptools_scm]
