[tool.mypy]
strict = true
show_error_codes = true

# Add Python modules to be ignored by mypy here
[[tool.mypy.overrides]]
module = [
    "chartjs.colors",  # Package: django-chartjs
    "chartjs.views.base",  # Package: django-chartjs
    "crispy_forms.helper",  # Package: django-crispy-forms
    "crispy_forms.layout",  # Package: django-crispy-forms
    "enumfields",  # Package: django-enumfields
    "enumfields.fields",  # Package: django-enumfields
    "fasteners",  # Package: fasteners
    "ffpuppet",  # Package: ffpuppet
    "fuzzing_decision.common.pool",  # Package: orion (Mozilla, needs FuzzManager types)
    "laniakea.core.providers.ec2",  # Package: laniakea (Mozilla, currently archived)
    "laniakea.core.providers.gce",  # Package: laniakea (Mozilla, currently archived)
    "laniakea.core.userdata",  # Package: laniakea (Mozilla, currently archived)
    "mozilla_django_oidc.auth",  # Package: mozilla-django-oidc
    "mozillapulse.consumers",  # Package: mozillapulse
    "notifications",  # Package: django-notifications-hq
    "notifications.models",  # Package: django-notifications-hq
    "notifications.signals",  # Package: django-notifications-hq
    "server.covmanager.models",  # Located here in server/covmanager/models.py
    "taskcluster",  # Package: taskcluster
    "S3Manager",  # Located here in misc/afl_libfuzzer/S3Manager.py
]
ignore_missing_imports = true
