# Generated by Django 4.2.27 on 2026-05-12 19:13

from django.db import migrations, models


def null_to_empty(apps, schema_editor):
    Instance = apps.get_model("ec2spotmanager", "Instance")
    Instance.objects.filter(hostname__isnull=True).update(hostname="")
    Instance.objects.filter(instance_id__isnull=True).update(instance_id="")
    Instance.objects.filter(status_data__isnull=True).update(status_data="")

    PoolConfiguration = apps.get_model("ec2spotmanager", "PoolConfiguration")
    for field in [
        "ec2_allowed_regions",
        "ec2_image_name",
        "ec2_instance_types",
        "ec2_key_name",
        "ec2_raw_config",
        "ec2_security_groups",
        "ec2_userdata_macros",
        "gce_args",
        "gce_cmd",
        "gce_container_name",
        "gce_env",
        "gce_image_name",
        "gce_machine_types",
        "gce_raw_config",
        "instance_tags",
    ]:
        PoolConfiguration.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: ""}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0002_auto_20210429_0908'),
    ]

    operations = [
        migrations.RunPython(null_to_empty, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='instance',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instance',
            name='instance_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_allowed_regions',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_instance_types',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_key_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_raw_config',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_security_groups',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_userdata_macros',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_args',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_cmd',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_container_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_env',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_machine_types',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='gce_raw_config',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolconfiguration',
            name='instance_tags',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
