# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models


def instance_types_to_list(apps, schema_editor):
    PoolConfiguration = apps.get_model("ec2spotmanager", "PoolConfiguration")
    for pool in PoolConfiguration.objects.all():
        pool.ec2_instance_types_list = [pool.ec2_instance_types]
        pool.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0006_auto_20150625_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_instance_type',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
        migrations.RenameField(
            model_name='poolconfiguration',
            old_name='ec2_instance_type',
            new_name='ec2_instance_types',
        ),
        migrations.RunPython(instance_types_to_list),
    ]
