# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0007_instance_type_to_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolconfiguration',
            name='aws_access_key_id',
        ),
        migrations.RemoveField(
            model_name='poolconfiguration',
            name='aws_secret_access_key',
        ),
    ]
