# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0009_add_instance_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolconfiguration',
            name='ec2_instance_types',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
