# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-12 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0010_extend_instance_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='ec2_instance_id',
            new_name='instance_id',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='ec2_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='ec2_zone',
            new_name='zone',
        ),
        migrations.RenameField(
            model_name='poolconfiguration',
            old_name='ec2_userdata_macros',
            new_name='userdata_macros',
        ),
        migrations.RenameField(
            model_name='poolconfiguration',
            old_name='ec2_userdata_file',
            new_name='userdata_file',
        ),
    ]
