# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ec2spotmanager', '0011_auto_20181012_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderStatusEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField()),
                ('msg', models.CharField(max_length=4095)),
                ('isCritical', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='provider',
            field=models.CharField(default='EC2Spot', max_length=255),
            preserve_default=False,
        )
    ]
