# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 04:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0001_squashed_0020_add_app_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={
                'permissions': (
                    ('view_crashmanager', 'Can see CrashManager app'),
                    ('view_covmanager', 'Can see CovManager app'),
                    ('view_ec2spotmanager', 'Can see EC2SpotManager app'),
                    ('view_taskmanager', 'Can see TaskManager app'),
                )
            },
        ),
    ]
