# Generated by Django 3.0.14 on 2021-04-29 09:08

import django.core.files.storage
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0002_add_taskmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='test',
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location=getattr(settings, 'TEST_STORAGE', None)
                ),
                upload_to='tests'
            ),
        ),
    ]
