# Generated by Django 3.0.14 on 2021-05-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0003_auto_20210429_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugprovider',
            name='classname',
        ),
    ]
