# Generated by Django 4.1.4 on 2022-12-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0007_buckethit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tasks_failed",
            field=models.BooleanField(default=False),
        ),
    ]
