# Generated by Django 4.1.5 on 2023-03-02 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0009_bucket_donotreduce"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrashHit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lastUpdate",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("count", models.BigIntegerField(default=0)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crashmanager.tool",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="crashhit",
            constraint=models.UniqueConstraint(
                fields=("lastUpdate", "tool"), name="unique_crashhits_per_tool"
            ),
        ),
    ]
