# Generated by Django 4.1.7 on 2023-06-21 20:15

import sys

from django.db import migrations


def grant_existing_perms(apps, schema_editor):
    # updating permissions in a migration is not straightforward
    # because new permissions are not actually committed until
    # the post_migrate signal
    # ref: https://stackoverflow.com/a/31543063
    cmUser = apps.get_model("crashmanager", "User")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("auth", "User")

    content_type = ContentType.objects.get_for_model(cmUser)

    for user in User.objects.all():
        added = []
        user_perms = {perm.codename for perm in user.user_permissions.all()}

        for app in ["crashmanager", "covmanager", "taskmanager", "ec2spotmanager"]:
            if f"view_{app}" in user_perms:
                user.user_permissions.add(
                    Permission.objects.get_or_create(
                        content_type=content_type, codename=f"{app}_all"
                    )[0]
                )
                added.append(f"{app}_all")

        if added:
            print(
                f"user {user.username} added permissions: {', '.join(added)}",
                file=sys.stderr,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0010_crashhit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    (
                        "view_crashmanager",
                        "Can see CrashManager app (required for crashmanager_* perms)",
                    ),
                    (
                        "view_covmanager",
                        "Can see CovManager app (required for covmanager_* perms",
                    ),
                    (
                        "view_ec2spotmanager",
                        "Can see EC2SpotManager app (required for ec2spotmanager_* "
                        "perms)",
                    ),
                    (
                        "view_taskmanager",
                        "Can see TaskManager app (required for taskmanager_* perms)",
                    ),
                    ("crashmanager_report_crashes", "Can report CrashManager crashes"),
                    ("crashmanager_download_signatures", "Can download signatures.zip"),
                    ("crashmanager_all", "Full access to CrashManager"),
                    ("covmanager_submit_collection", "Can submit coverage data"),
                    ("covmanager_all", "Full access to CovManager"),
                    ("taskmanager_report_status", "Can report TaskManager status"),
                    ("taskmanager_all", "Full access to TaskManager"),
                    (
                        "ec2spotmanager_report_status",
                        "Can report EC2SpotManager status",
                    ),
                    ("ec2spotmanager_all", "Full access to EC2SpotManager"),
                )
            },
        ),
        migrations.RunPython(
            grant_existing_perms,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
