# Generated by Django 4.2.13 on 2024-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coverage_drop",
            field=models.BooleanField(default=False),
        ),
    ]
