# Generated by Django 4.2.8 on 2024-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0012_user_coverage_drop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AddConstraint(
            model_name="os",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_os_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="unique_product_version"
            ),
        ),
    ]
