# Generated by Django 4.2.13 on 2024-09-09 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0014_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": (
                    (
                        "view_crashmanager",
                        "Can see CrashManager app (required for crashmanager_* perms)",
                    ),
                    (
                        "view_taskmanager",
                        "Can see TaskManager app (required for taskmanager_* perms)",
                    ),
                    ("crashmanager_report_crashes", "Can report CrashManager crashes"),
                    ("crashmanager_download_signatures", "Can download signatures.zip"),
                    ("crashmanager_all", "Full access to CrashManager"),
                    ("taskmanager_report_status", "Can report TaskManager status"),
                    ("taskmanager_all", "Full access to TaskManager"),
                )
            },
        ),
    ]
