# Generated by Django 4.2.8 on 2024-10-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("crashmanager", "0015_bucket_reassign_in_progress"),)

    operations = (
        migrations.AlterField(
            model_name="crashentry",
            name="testcase",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crashmanager.testcase",
            ),
        ),
    )
