# Generated by Django 4.2.13 on 2024-09-09 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crashmanager", "0016_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="coverage_drop",
        ),
    ]
