# Generated by Django 4.2.13 on 2025-03-17 20:25

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations, models


def populate_statistics(apps, schema_editor):
    call_command("populate_bucket_statistics", force=True)


class Migration(migrations.Migration):

    dependencies = [
        ("crashmanager", "0017_buckethit_unique_buckethits_per_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="BucketStatistics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(default=0)),
                ("quality", models.IntegerField(null=True)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crashmanager.bucket",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crashmanager.tool",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bucketstatistics",
            constraint=models.UniqueConstraint(
                fields=("bucket", "tool"), name="unique_bucketstats_per_tool"
            ),
        ),
        migrations.RunPython(populate_statistics),
    ]
