# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0018_auto_20170620_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='optimizedSignature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
