# Generated by Django 4.2.27 on 2026-05-12 19:13

from django.db import migrations, models


def null_to_empty(apps, schema_editor):
    Bucket = apps.get_model("crashmanager", "Bucket")
    Bucket.objects.filter(optimizedSignature__isnull=True).update(optimizedSignature="")

    CrashEntry = apps.get_model("crashmanager", "CrashEntry")
    CrashEntry.objects.filter(cachedCrashInfo__isnull=True).update(cachedCrashInfo="")

    # Product and OS have a unique constraint on (name, version). Multiple rows with
    # version=NULL are distinct in SQL (NULL != NULL), but would collide after converting
    # to ''. Deduplicate by keeping the lowest-pk row per name and re-pointing any
    # CrashEntry FK references before deleting the extras.
    for model_name, fk_field in [("Product", "product"), ("OS", "os")]:
        Model = apps.get_model("crashmanager", model_name)
        canonical = {}
        for obj in Model.objects.filter(version__isnull=True).order_by("pk"):
            if obj.name in canonical:
                CrashEntry.objects.filter(
                    **{f"{fk_field}_id": obj.pk}
                ).update(**{f"{fk_field}_id": canonical[obj.name]})
                obj.delete()
            else:
                canonical[obj.name] = obj.pk
        Model.objects.filter(version__isnull=True).update(version="")


class Migration(migrations.Migration):

    dependencies = [
        ('crashmanager', '0019_alter_user_options'),
    ]

    operations = [
        migrations.RunPython(null_to_empty, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bucket',
            name='optimizedSignature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crashentry',
            name='cachedCrashInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='os',
            name='version',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
