# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covmanager', '0003_collection_file_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('directives', models.TextField()),
                ('public', models.BooleanField(default=False)),
                ('logical_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='covmanager.ReportConfiguration')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 to='covmanager.Repository')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cached_result', models.TextField(blank=True, null=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                    to='covmanager.Collection')),
            ],
        ),
    ]
