# Generated by Django 3.0.14 on 2021-04-29 09:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covmanager', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionfile',
            name='file',
            field=models.FileField(
                max_length=255,
                storage=django.core.files.storage.FileSystemStorage(location=None),
                upload_to='coverage'
            ),
        ),
    ]
