# Generated by Django 4.2.7 on 2024-03-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("covmanager", "0006_auto_20210429_0908"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="tag",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
