# Generated by Django 4.2.13 on 2024-09-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("reportmanager", "0001_initial"),)

    operations = (
        migrations.AlterField(
            model_name="reportentry",
            name="comments",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reportentry",
            name="url",
            field=models.URLField(max_length=8192),
        ),
    )
