# Generated by Django 4.2.13 on 2024-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("reportmanager", "0002_alter_reportentry_comments_alter_reportentry_url"),
    )

    operations = (
        migrations.AddField(
            model_name="bucket",
            name="description",
            field=models.TextField(default="blah"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bucket",
            name="domain",
            field=models.TextField(null=True),
        ),
    )
