# Generated by Django 4.2.13 on 2024-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("reportmanager", "0003_bucket_description_bucket_domain"),)

    operations = (
        migrations.AddConstraint(
            model_name="buckethit",
            constraint=models.UniqueConstraint(
                fields=("bucket", "begin"), name="unique_buckethits"
            ),
        ),
    )
