# Generated by Django 4.2.13 on 2024-09-20 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("reportmanager", "0005_alter_bucket_domain"),)

    operations = (
        migrations.RemoveField(
            model_name="bucket",
            name="snooze_until",
        ),
        migrations.CreateModel(
            name="BucketWatch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_report", models.IntegerField(default=0)),
                (
                    "bucket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reportmanager.bucket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reportmanager.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="buckets_watching",
            field=models.ManyToManyField(
                through="reportmanager.BucketWatch", to="reportmanager.bucket"
            ),
        ),
    )
