# Generated by Django 4.2.27 on 2026-05-12 19:13

from django.db import migrations, models


def null_to_empty(apps, schema_editor):
    Pool = apps.get_model("taskmanager", "Pool")
    Pool.objects.filter(cpu__isnull=True).update(cpu="")

    Task = apps.get_model("taskmanager", "Task")
    Task.objects.filter(decision_id__isnull=True).update(decision_id="")


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_allow_unknown_task_status_and_run_time_calculation'),
    ]

    operations = [
        migrations.RunPython(null_to_empty, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pool',
            name='cpu',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='decision_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
